#
# Hugo configuration
#
# Settings that influence Hugo build process and DocDock theme behaviour.
#

baseURL = "/"
# languageCode = "en-us"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"

title = "Indienet"
theme = "docdock"

# This allows pages to get the last modified time from git.
enableGitInfo = "true"

[params]
editURL = "https://source.ind.ie/indienet/docs/tree/master/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

# This enables the index.json file used by the Lunr-based search
# to be generated at build time.
[outputs]
home = [ "HTML", "RSS", "JSON"]

#
# You may add other languages here.
#

[languages]
[languages.en]
weight = 1
languageName = "English"

[[languages.en.menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-heart'></i> Indienet"
identifier = "indienet"
url = "https://source.ind.ie/indienet"
weight = 10

[[languages.en.menu.shortcuts]]
name = "<i class='fa fa-git-square'></i> View source"
identifier = "ds"
url = "https://source.ind.ie/indienet/docs"
weight = 20
